#ifndef SEEDLESSDS_GPU_GPU3D_GXFIFO_STATE_PRIMITIVE_TABLE_H
#define SEEDLESSDS_GPU_GPU3D_GXFIFO_STATE_PRIMITIVE_TABLE_H

#include <stdint.h>

#define GXFIFO_STATE_PRIMITIVE_TABLE_BYTES 4096u

extern const uint8_t gxfifo_state_primitive_table[GXFIFO_STATE_PRIMITIVE_TABLE_BYTES];

#endif
