#ifndef SEEDLESSDS_FRONTEND_AUDIO_OUT_SILENCE_H
#define SEEDLESSDS_FRONTEND_AUDIO_OUT_SILENCE_H

#define AUDIO_OUT_SILENCE_COUNT 5880

extern const int16_t audio_out_silence[AUDIO_OUT_SILENCE_COUNT];

#endif
