#ifndef SEEDLESSDS_FRONTEND_MIC_DEFAULT_SAMPLE_H
#define SEEDLESSDS_FRONTEND_MIC_DEFAULT_SAMPLE_H

#define MIC_DEFAULT_SAMPLE_COUNT 22050
#define MIC_DEFAULT_SAMPLE_BYTES (MIC_DEFAULT_SAMPLE_COUNT * 2)

extern const int16_t mic_default_sample[MIC_DEFAULT_SAMPLE_COUNT];

#endif
