#ifndef SEEDLESSDS_CORE_INTERNALS_H
#define SEEDLESSDS_CORE_INTERNALS_H

#include <stdarg.h>
#include <stddef.h>
#include <stdint.h>
#include <sys/types.h>
#include <time.h>

typedef struct arm arm_t;
typedef struct bus_region bus_region_t;
typedef struct bus bus_t;
typedef struct cart cart_t;
typedef struct cheat_entry cheat_entry_t;
typedef struct cheats cheats_t;
typedef struct cp15 cp15_t;
typedef struct dma_channel dma_channel_t;
typedef struct dma dma_t;
typedef struct firmware_header firmware_header_t;
typedef struct game_database game_database_t;
typedef struct gl_recipe_tag gl_recipe_tag_t;
typedef struct gl_renderer gl_renderer_t;
typedef struct gpu2d_bg gpu2d_bg_t;
typedef struct gpu2d_engine gpu2d_engine_t;
typedef struct gpu3d_band_bucket gpu3d_band_bucket_t;
typedef struct gpu3d_bank_vertex gpu3d_bank_vertex_t;
typedef struct gpu3d_polygon_list gpu3d_polygon_list_t;
typedef struct gpu3d_polygon gpu3d_polygon_t;
typedef struct gpu3d gpu3d_t;
typedef struct gpu3d_texture_cache gpu3d_texture_cache_t;
typedef struct gpu3d_texture_entry gpu3d_texture_entry_t;
typedef struct gpu_output gpu_output_t;
typedef struct gpu gpu_t;
typedef struct jit_emitter jit_emitter_t;
typedef struct nds nds_t;
typedef struct rtc rtc_t;
typedef struct sched sched_t;
typedef struct script_io script_io_t;
typedef struct slot2_gpio slot2_gpio_t;
typedef struct slot2_sensor slot2_sensor_t;
typedef struct slot2 slot2_t;
typedef struct spi_memory spi_memory_t;
typedef struct spi spi_t;
typedef struct spi_tsc spi_tsc_t;
typedef struct spu spu_t;
typedef struct vram_map vram_map_t;

void cart_backup_init_paths(cart_t *cart, unsigned char *ctx);
void * cart_backup_reset_zone_defaults(cart_t *cart);
uint64_t cart_boot_from_header(cart_t *ctx);
void cart_command_execute(cart_t *ctx, uint32_t arg);
uint32_t cart_data_in_next_word(cart_t *obj);
void cart_data_transfer_step(cart_t *obj, uint32_t word);
void * cart_header_logo_copy(unsigned char *dest, const unsigned char *origin);
uint64_t cart_homebrew_setup_argv(cart_t *cart);
uint32_t cart_slot2_descriptor_next_field(slot2_sensor_t *sensor, uint32_t value);
int cart_slot2_gpio_countdown_tick(slot2_gpio_t *gpio);
void cart_slot2_gpio_set_bit1(slot2_gpio_t *gpio, uint32_t v);
uint32_t cart_slot2_queue_pop_2bit(slot2_sensor_t *sensor);
void cart_transfer_irq_raise(void *unused, void *argument);
void cart_key1_apply_keycode(cart_t *obj);
uint32_t cart_key1_decrypt_secure_area(cart_t *ctx, unsigned char *area, uint64_t x2_unused, const void *table);
uint32_t cart_key1_encrypt_secure_area(cart_t *ctx, unsigned char *area, uint64_t x2_unused, const void *table);
long cart_slot2_backup_autosave_tick(slot2_t *obj);
uint32_t cart_slot2_backup_read_byte(const slot2_t *sub, uint32_t dir);
void cart_slot2_backup_write_byte(slot2_t *sub, uint32_t dir, uint32_t value);
int32_t cart_slot2_load_gba(cart_t *cart, const char *name);
int cart_slot2_map_gpio_region_arm9(unsigned char *ctx);
uint32_t cart_slot2_map_region_both_cpus(void *param_1);
int benchmark_format_run_time(char *dest, long a, long b, ...);
void * gamedb_apply_fixes(unsigned char *o);
int jni_system_store_formatted_message(long a0, long a1, long a2, long a3, ...);
struct arm_debug;
void arm_debug_reset(struct arm_debug *debug);
int nds_close_files(cart_t *cart);
unsigned long nds_loading_percent(void);
void nds_machine_init(unsigned char *obj);
void nds_machine_reset(unsigned char *machine);
int nds_sprintf_limited(char *dest, size_t size, const char *format, ...);
void nds_subsystem_hook_noop(void);
void audio_out_restart_playback(void);
void nds_subsystem_shutdown_release_objects(void);
void pacer_init(unsigned char *ctx);
void pacer_run(uint8_t *ctx);
void sched_advance(unsigned char *machine);
void sched_deadline_insert(sched_t *base, uint32_t deadline, uint32_t idx);
void sched_deadline_set(sched_t *base, uint32_t idx, void (*callback)(void *machine, void *argument), void *argument);
void sched_deadline_remove(sched_t *base, uint32_t idx);
void sched_deadlines_clear(sched_t *base);
uint64_t sched_dispatch_next(uint8_t *machine);
uint64_t sched_dispatch_arm7(uint8_t *machine);
void dma_transfer_end_event(void *unused, void *argument);
void sched_event_insert(void *obj, void *argument);
void * sched_init(sched_t *obj, unsigned char *ctx);
void sched_scanline_event(void *machine, void *argument);
unsigned char * state_read_cart_block(cart_t *cart, unsigned char *reader, uint32_t mode);
void state_read_cpu_block(uint8_t *dst, uint8_t *arg);
void state_read_gpu3d_block(void *param_1, void *param_2, uint32_t param_3);
void state_read_machine_blocks(uint8_t *machine, uint8_t *stream, uint32_t mode);
void state_read_memory_blocks(bus_t *bus, uint8_t *stream, uint32_t mode);
void * state_read_sched_block(sched_t *param_1, uint8_t *param_2, uint32_t param_3);
void state_read_spi_memory_data(spi_memory_t *m, uint8_t *reader);
void state_read_spi_memory_status(spi_memory_t *m, unsigned char *reader);
void * state_read_spu_block(spu_t *spu, uint8_t *entry, uint32_t mode);
int32_t state_save_file(uint8_t *machine, const char *path, const char *name_final, const void *copy_a, const void *copy_b);
int32_t state_save_slot_with_screens(uint32_t param_1);
void state_write_cart_block(cart_t *cart, unsigned char *desc, uint32_t mode);
void state_write_cpu_block(void *param_1, void *param_2);
void *state_write_finish(void *arg);
void state_write_gpu3d_block(unsigned char *param_1, unsigned char *param_2, uint32_t param_3);
void state_write_machine_blocks(uint8_t *machine, uint8_t *stream, uint32_t mode);
void * state_write_memory_blocks(unsigned char *ctx, unsigned char *output, uint32_t mode);
uint32_t state_write_pending(void);
void state_write_sched_block(void *param_1, void *param_2);
void state_write_spi_memory_data(const spi_memory_t *m, uint8_t *writer);
void state_write_spu_block(const spu_t *spu, unsigned char *obj);
void state_write_three_words(unsigned char *param_1, unsigned char *param_2);
void arm_cpsr_set(unsigned char *cpu, uint32_t cpsr);
void arm_exception_raise(unsigned char *machine, uint32_t order);
void arm_halt_enter(arm_t *cpu);
void arm_hook_noop(void);
void arm_init(unsigned char *obj, unsigned char *ctx, uint32_t idx, void *pair);
void arm_reset(unsigned char *o);
uint32_t arm_thumb_to_arm(uint32_t param_1, void *param_2);
void bus_access_tables_init(bus_t *bus);
void bus_range_mark_written(unsigned char *ctx, uint32_t address, uint32_t size);
unsigned bus_read16_slow(uint8_t *state, unsigned dir);
uint64_t bus_read32_slow(uint8_t *ctx, uint32_t dir);
unsigned bus_read8_slow(uint8_t *state, unsigned dir);
void * bus_region_init_channel_descriptors(bus_t *bus);
void bus_region_init_mirror_pair_and_flush(uint8_t *ctx);
void bus_region_init_queue_descriptors(void *param_1);
void * bus_region_page_lookup(bus_t *a, bus_region_t *b, unsigned int idx);
void bus_region_reset_and_free(bus_t *bus);
void * bus_region_slot_lookup_by_time(bus_t *param_1, bus_region_t *param_2, unsigned int param_3);
int bus_regions_alloc(unsigned char *ctx);
uint32_t bus_regions_init(uint8_t *machine);
void bus_write16_slow(uint8_t *state, unsigned dir, unsigned value);
void bus_write32_slow(uint8_t *state, unsigned dir, unsigned value);
void bus_write8_slow(uint8_t *state, unsigned dir, unsigned value);
void cheats_apply_active(void *machine, cheats_t *list, uint32_t mask);
void cheats_run_codes(uint8_t *machine, cheat_entry_t *descriptor, uint32_t mask);
void cp15_bind(cp15_t *cp, arm_t *arm);
int cp15_control_apply(cp15_t *cp);
void cp15_load_state(cp15_t *cp, unsigned char *state, uint32_t limit);
void cp15_reset(cp15_t *cp);
uint32_t * jit_block_analyze(void *ctx_v, uint32_t dir, uint32_t thumb_arg);
void jit_arena_protect_rwx(unsigned char *base);
void * jit_arena_regions_pair0(unsigned char *base);
void * jit_arena_regions_pair1(unsigned char *base);
void jit_arena_regions_pair2(unsigned char *ctx);
void * jit_block_lookup(void *param_1, uint32_t param_2);
void * jit_cache_lookup_or_compile(void *ctx, uint32_t dir);
void jit_cache_refresh_block_info(unsigned char *ctx);
void jit_link_pending_branches(void *ctx);
uint32_t jit_watch_write16(unsigned char *machine, uint32_t dir);
uint32_t jit_watch_write32(unsigned char *machine, uint32_t dir);
uint32_t jit_watch_write8(unsigned char *machine, uint32_t dir);
uint32_t jit_watch_write_notify(unsigned char *machine, uint32_t dir);
uint32_t * jit_emit_block(void *param_1, void *param_2, uint32_t param_3, uint32_t param_4);
uint32_t jit_emit_encode_logical_imm(uint32_t param_1, void *param_2, void *param_3);
void jit_emit_instruction(jit_emitter_t *machine);
void jit_emit_link_queue_entry(jit_emitter_t *ctx);
uint32_t jit_emit_operand_word(void *ctx, uint32_t desc, uint32_t mode, uint32_t val);
void pagetable_clip_write(unsigned char *machine, uint32_t dir, uint32_t len);
void pagetable_unmap_range(unsigned char *t, uint32_t dir, uint32_t len);
void geolog_write_frame_dump(gpu3d_t *ctx);
void dma_transfer_copy_via_pagetable(dma_t *machine, dma_channel_t *channel);
void * archive_7z_extract_by_extension(const char *path, const char *suffix, uint32_t *output_size, const char *dest);
int archive_7z_read_range(const char *container, const char *extension, uint32_t *found_size, void *dest, uint32_t dest_size, int32_t offset);
uint64_t archive_7z_window_sink_write(void *sink, const void *data, uint64_t size);
void * archive_open_rom(const char *path, const char *cache, uint32_t clip, uint32_t private);
void * archive_rar_extract_by_extension(const char *param_1, const char *extension, uint32_t *output_size, const char *param_4);
int archive_rar_file_sink_write(int32_t param_1, void *param_2, const void *param_3, uint64_t param_4);
int32_t archive_rar_memory_sink_write(int32_t mode, uint64_t *cursor, const void *src, uint64_t n);
int archive_rar_read_range(const char *name_file, const char *extension, uint32_t *output_size, void *dest, int len, int offset);
int archive_rar_window_sink_write(const unsigned char *param_1, int param_2);
uint32_t archive_rom_classify_header(const char *path);
int archive_rom_read_chunk(const char *path, uint32_t *out_size, void *dest, uint32_t len, uint32_t shift);
void archive_vsnprintf_limited(char *dest, long unused, size_t maxlen, const char *format, ...);
void * archive_zip_extract_entry(const char *path, const char *name, uint32_t *size_output, const char *dest);
int32_t archive_zip_find_entry(int32_t descriptor, const char *name, void *param_3, uint32_t max);
int32_t archive_zip_open_entry(const char *path, const char *name, uint32_t *output, void *dest, uint32_t count, uint32_t jump);
uint32_t archive_zip_read_sector(void *param_1, uint8_t **param_2);
int32_t archive_zip_window_sink_write(void *sink, uint8_t *src, uint32_t delta);
void audio_out_flush_queues(void);
int audio_out_stop_and_mute(spu_t *spu);
int audio_out_load_wav(spu_t *spu, const char *path);
void audio_out_queue_callback(void *caller, void *context);
void audio_out_set_volume_db(uint32_t vol);
void audio_out_set_volume_level(int32_t level);
int audio_out_start(unsigned char *machine);
unsigned int cheats_find_interned_entry(cheats_t *state, const void *data, unsigned int n_words);
int32_t cheats_load_entry_by_key(cheats_t *state, uint32_t key, uint32_t subkey);
int cheats_load_user_file(cheats_t *p, unsigned char *obj);
void * cheats_rebuild_active_list(cheats_t *g);
uint32_t cheats_remove_entry(void *obj, uint32_t idx);
int cheats_save_record(cheats_t *param_1);
uint32_t cheats_write_user_file(cheats_t *state, nds_t *nds);
void * db_find_cartridge_entry(const game_database_t *catalog, uint32_t key, const char *name);
int32_t db_load_cartridge_database(game_database_t *out, const char *path);
int db_load_cheat_index(cheats_t *obj, const char *path);
int db_vsprintf_limited(char *dest, size_t size, const char *format, ...);
void db_xml_escape_string(uint8_t *output, const uint8_t *entry);
int32_t db_xml_read_tag(void *fp, uint8_t *state, char *err);
void db_xml_unescape_string(char *output, const char *entry, unsigned n, unsigned size);
void input_state_reset(void);
void input_record_reset_state(unsigned char *obj, void *ctx);
void mic_capture_queue_callback(void *caller, void *context);
int mic_init_recorder(long param_1);
void jit_hook_register_dual_slot(unsigned char *machine, void *arg);
int32_t script_run_file(const char *path);
uint32_t script_cursor_push_float(void *obj, float value);
uint32_t script_cursor_push_int(void *obj, uint32_t value);
int script_lua_init(unsigned char *machine);
uint32_t script_lua_read_integer_arg(void *param_1, uint32_t *param_2);
void script_run_on_frame_update(void);
void script_run_on_unload(void);
int video_out_shader_load_and_report_errors(const char *param_1, void *param_2, void *param_3);
int video_out_shader_parse_source_blocks(void *fp, void *param_2_no_used, void **out_vertex, void **out_fragment, void **parts);
void * script_io_consume_outputs(uint32_t *dest);
void script_io_init(void);
void * script_io_publish_inputs(script_io_t *obj);
void script_io_reset(void);
void video_out_dump_screen_rgb565(void *dest, unsigned int screen);
uint32_t video_out_get_screen_mode(uint32_t i);
void video_out_layer_toggle_hook_noop(void);
void video_out_option_toggle_hook_noop(void);
unsigned int video_out_pixel_size(void);
void video_out_prepare_scale_axes(uint8_t *state);
void * video_out_screen_buffer(unsigned int screen);
int video_out_screen_line_size(unsigned int screen);
void video_out_gl_call_renderer_object_slot0(int a, int b, int c, int d, int e, int f);
void video_out_gl_call_renderer_object_slot1(int a, int b, int c, int d, int e, int f);
void * video_out_gl_clear_framebuffers(void *arg);
void video_out_gl_clear_screens(unsigned texture_a, unsigned texture_b);
int video_out_gl_context_init(void);
void video_out_gl_draw_screen_rect2(uint32_t texture, uint32_t idx);
void video_out_gl_draw_screen_rect4(uint32_t texture, uint32_t idx);
int video_out_gl_format_log_path(char *param_1, long param_2, long param_3, long param_4, ...);
int32_t video_out_gl_load_shader_recipe(const char *path, gl_renderer_t *ctx, void *val3, void *val4);
void video_out_gl_render_frame(uint32_t param_1, uint32_t param_2, uint32_t param_3, uint32_t param_4, uint32_t param_5, uint32_t param_6, uint32_t param_7, uint32_t param_8, uint32_t param_9, uint32_t param_10);
void video_out_gl_render_single_screen(uint64_t texture, uint32_t idx, uint32_t param_3, uint32_t param_4, uint32_t param_5, uint32_t param_6);
void video_out_gl_renderer_release(void *param_1, int32_t param_2);
void video_out_gl_renderer_resize_nodes(void *param_1, uint32_t param_2, uint32_t param_3, uint32_t param_4, uint32_t param_5, uint32_t param_6, uint32_t param_7);
void video_out_gl_set_texture_format(int32_t bpp);
void video_out_gl_shader_recipe_extract_value(const char *line, char *dest, uint64_t size);
void * video_out_gl_shader_recipe_read_block(void *fp, const char *needle, void *param_3, void *param_4);
int32_t video_out_gl_shader_recipe_read_include(gl_renderer_t *ctx, void *f, char *line, const gl_recipe_tag_t *tag);
int32_t video_out_gl_shader_recipe_read_options(gl_renderer_t *r, void *stream, char *buf, const gl_recipe_tag_t *tag);
int32_t video_out_gl_shader_recipe_read_pass(gl_renderer_t *r, void *stream, char *buf, const gl_recipe_tag_t *tag);
int32_t video_out_gl_shader_recipe_read_text_block(gl_renderer_t *obj, void *f, char *buf, const gl_recipe_tag_t *tag);
int32_t video_out_gl_shader_recipe_read_texture(gl_renderer_t *r, void *stream, char *line, const gl_recipe_tag_t *tag);
uint32_t video_out_gl_token_lookup(const char *param_1);
void gpu_hud_stats_format(long x0_unused, long x1_unused, long x2_unused, ...);
void gpu_vblank_dispatch(void *machine, void *argument);
uint32_t gpu2d_bg_affine_merge_texcoord_runs(uint8_t *param_1, uint8_t *param_2, uint8_t *param_3, uint32_t param_4, uint32_t param_5);
int32_t gpu2d_bg_affine_render_span_batched(uint8_t *ctx, uint8_t *spans, void *p3, void *p4, void *p5, void *p6, uint32_t ox, uint32_t oy, int32_t n);
int32_t gpu2d_bg_affine_render_span_scalar(uint8_t *ctx, uint8_t *spans, void *p3, void *p4, void *p5, uint64_t dead, uint32_t ox, uint32_t oy, uint32_t n);
void gpu2d_bg_affine_sample_bitmap_affine_line(gpu2d_bg_t *p1, uint8_t *dst, uint8_t *info, uint32_t line);
void gpu2d_bg_text_cache_direct_ptr(gpu2d_engine_t *ctx, uint32_t layer);
void gpu2d_bg_text_decode_indexed_line(gpu2d_bg_t *ctx, uint8_t *dest16, uint8_t *mask, uint32_t line);
void gpu2d_bg_text_expand_mask_words(void *param_1, uint32_t param_2);
void gpu2d_bg_text_identity(gpu2d_bg_t *bg, uint8_t *dst, uint8_t *mask, uint32_t line);
void gpu2d_bg_text_mask_bit_range256(uint32_t *map, unsigned from, unsigned until);
void gpu2d_blend_apply_alpha(uint8_t *dest, const uint8_t *sources, const uint8_t *weightA, const uint8_t *weightB);
void gpu2d_blend_weights_from_alpha_line(unsigned char *out_plus, unsigned char *out_inv, const unsigned char *data, const unsigned char *mask);
void gpu2d_blend_weights_from_alpha_masked(unsigned char *bufA, unsigned char *bufB, const unsigned char *src, const unsigned char *mask);
void gpu2d_line_apply_flat_color_masked(uint16_t *dest, const uint16_t *origin, int color, const uint32_t *mask);
void gpu2d_compose_blend_line_windows(uint8_t *ctx, uint8_t *dst, uint8_t *w, void *p4, void *p5, void *p6, uint32_t layers, uint32_t sel, uint32_t band);
void gpu2d_compose_blend_marked_layers(uint8_t *ctx, void *output, uint8_t *layers, uint8_t *lists, void *extra, void *extra2, uint32_t mask);
void gpu2d_compose_clear_masked_groups(const uint8_t *ctx, uint32_t *dest, const uint32_t *source, uint32_t mask);
void gpu2d_compose_convert_planes_to_rgb555_blend(void *state, void *dest, void *mix, void *planes);
void gpu2d_compose_decode_bg_row_8bpp_paletted(uint8_t *x0, uint8_t *x1, uint8_t *x2, uint8_t *x3, uint8_t *x4, int32_t x5, uint8_t *x6);
void gpu2d_compose_dispatch_layer_mix(gpu2d_engine_t *layer, uint8_t *output, uint8_t *coverage, void *extra, uint32_t filter, uint32_t prio);
void gpu2d_compose_extract_alpha_plane(unsigned char *dst, const unsigned char *src);
int gpu2d_compose_fold_alpha_summary(uint8_t *dest, const void *origin);
void gpu2d_compose_gen_row_ramp_halfword(uint16_t *dst, unsigned char *tables, uint32_t rows, const uint32_t *steps);
void gpu2d_compose_gen_row_ramp_q30(uint32_t *param_1, unsigned char *param_2, int32_t param_3, const int32_t *param_4);
void gpu2d_compose_pack_flag_mask_odd_bytes(unsigned char *dst, const unsigned char *src, int32_t n);
uint32_t gpu2d_compose_render_line(void *ctx, uint8_t *dst, uint32_t line, gpu_output_t *cap, uint32_t doubled);
void * gpu2d_compose_scroll_line_h(void *dst, const void *src, int n);
void gpu2d_window_regions_apply_three(unsigned char *table, unsigned char *param_2, uint32_t param_3, const unsigned char *param_4, const unsigned char *param_5, uint32_t param_6, uint32_t param_7, uint32_t param_8);
void gpu2d_window_regions_apply_two(unsigned char *table, unsigned char *param_2, uint32_t param_3, const unsigned char *param_4, uint32_t param_5, uint32_t param_6);
void gpu2d_engine_init_substructures(gpu2d_engine_t *o);
void gpu2d_engine_load_state_registers(gpu2d_engine_t *ctx, uint8_t *entry, uint32_t count);
void gpu2d_engine_save_state_registers(const gpu2d_engine_t *param_1, unsigned char *param_2, uint32_t param_3);
void gpu2d_engine_write_bgcnt(gpu2d_engine_t *ctx, uint32_t layer, uint32_t value);
void gpu2d_engine_write_dispcnt(gpu2d_engine_t *obj, unsigned value);
void gpu2d_engine_write_register(gpu2d_engine_t *obj, const void *request);
void gpu2d_line_compute_span_range3(int32_t x, int32_t a, int32_t b, int32_t c, int64_t *out_a, int64_t *out_b, int64_t *out_c);
void gpu2d_block_delta_encode_inplace(unsigned char *buf, uint32_t off, uint32_t mark);
void gpu2d_palette_apply_lut64_lines(uint8_t *dest, const uint8_t *origin, const uint8_t *counts, const uint8_t *indices, int lines, const uint8_t *palettes);
void gpu2d_palette_indices_to_rgba_line(unsigned char *machine, const gpu3d_t *tables, const gpu3d_polygon_t *obj, uint32_t *dst, const unsigned char *src, uint32_t step, uint32_t height, uint32_t n);
void gpu2d_palette_lookup_line_idx12(uint32_t *dst, const uint16_t *src, const unsigned char *table, int32_t n);
void gpu2d_palette_lookup_line_idx8(uint32_t *dst, const unsigned char *src, const unsigned char *table, int32_t n);
void gpu2d_blend_weights_from_bldalpha_masked(int param_1, uint8_t *param_2, uint8_t *param_3, const uint16_t *param_4);
void gpu2d_planes_combine_six_masks(uint8_t *output, const uint8_t *masks, int flags, int modes);
void gpu2d_planes_expand_mask_to_params(int arg, uint8_t *table_a, uint8_t *table_b, const uint16_t *bits);
void gpu2d_planes_mask_from_bytes(uint8_t *mask, const uint8_t *pixels);
void gpu2d_planes_mask_from_pixels_lowbyte(uint8_t *mask, const uint16_t *pixels);
void gpu2d_planes_render_shadow_and_zero(int32_t param_1, uint64_t param_2, uint64_t param_3, uint32_t *param_4);
void gpu2d_planes_render_shadow_mirror_zero(int32_t param_1, uint64_t param_2, uint64_t param_3, uint64_t param_4, const uint32_t *param_5);
void gpu2d_window_x_mask_build(uint32_t *param_1, uint32_t param_2);
void gpu2d_worker_init(unsigned char *obj, unsigned char *ctx);
void gpu2d_worker_reset_engine_entries(uint8_t *engine, uint8_t *state, uint32_t value);
void gpu2d_worker_save_state_chain(const unsigned char *param_1, unsigned char *param_2, uint32_t param_3);
void gpu2d_worker_shutdown(void);
int gpu2d_worker_signal_request_bit(uint32_t bit);
void * gpu2d_worker_thread_loop(unsigned char *base);
void gpu3d_geometry_apply_lighting(gpu3d_t *ctx);
void gpu3d_geometry_clip_polygon(gpu3d_t *ctx, const uint8_t *desc, uint32_t n);
uint32_t gpu3d_geometry_color_expand_bgr555_alpha_bit15(uint64_t param_1);
uint32_t gpu3d_geometry_color_expand_bgr555_to_rgb8(uint32_t color);
uint32_t gpu3d_geometry_color_expand_bgr555_to_rgb8_alpha(uint32_t color, uint32_t alpha);
void gpu3d_geometry_emit_draw_entries(gpu3d_t *ctx, const uint8_t *desc, uint32_t step, uint32_t x, uint32_t diff, uint32_t alternate);
void * gpu3d_geometry_palette_build_alpha_ramp_table(uint8_t *ctx, const uint16_t *colors);
unsigned char * gpu3d_geometry_poly_split_runs(gpu3d_t *ctx, unsigned char *output, const unsigned char *src, uint32_t step, const unsigned char *ma, const unsigned char *mb, uint32_t mask);
void gpu3d_geometry_vertex_submit_with_texcoord(gpu3d_t *ctx, int x, int y, int z);
void * gpu3d_matrix_transform_vectors3(void *param_1, const void *param_2, const void *param_3);
void gpu3d_init_color_product_tables(gpu3d_t *ctx);
void gpu3d_context_subblock_init(gpu3d_t *obj, nds_t *machine, gpu3d_texture_cache_t *texture_cache);
void gpu3d_gxfifo_decode_commands(gpu3d_t *ctx, uint32_t *param_2, uint32_t param_3);
uint32_t gpu3d_gxfifo_decode_commands_with_cycles(gpu3d_t *ctx, uint32_t *param_2, uint32_t param_3);
void gpu3d_gxfifo_execute(gpu3d_t *ctx, unsigned int n);
void gpu3d_gxfifo_frame_end(gpu3d_t *ctx);
void gpu3d_gxfifo_pack_command(gpu3d_t *ctx, uint64_t param_2, uint32_t param_3);
void gpu3d_gxfifo_push_word(gpu3d_t *state, unsigned word);
void gpu3d_gxfifo_trace_buffer_rewind(gpu3d_t *obj);
void gpu3d_state_read_block(void *param_1, void *param_2);
void gpu3d_state_read_record32(unsigned char *param_1, unsigned char *param_2);
uint32_t gpu3d_io3d_clipmtx_result_read(gpu3d_t *obj, uint32_t n);
uint32_t gpu3d_io3d_gxstat_read(gpu3d_t *obj);
uint32_t gpu3d_io3d_ram_count_read(gpu3d_t *obj);
uint32_t gpu3d_io3d_vecmtx_result_read(gpu3d_t *obj, uint32_t n);
uint32_t gpu3d_ram_count_polygons_read(gpu3d_t *obj);
void gpu3d_matrix_mult_4x3(int32_t *output, const int32_t *a, const int32_t *b);
void gpu3d_matrix_mult_4x4_neon(int32_t *output, const int32_t *a, const int32_t *b);
void gpu3d_raster_band_attr_tables_build(unsigned char *machine, uint32_t base, uint32_t rows);
void gpu3d_raster_band_attr_tables_build_wide(unsigned char *machine, int32_t base, int32_t rows);
void gpu3d_raster_band_bucket_classify(gpu3d_t *machine, gpu3d_band_bucket_t *list, gpu3d_polygon_list_t *objs, gpu3d_bank_vertex_t *ent, uint32_t mode);
void gpu3d_raster_band_bucket_classify_by_depth(gpu3d_t *machine, gpu3d_band_bucket_t *list, gpu3d_polygon_list_t *objs, gpu3d_bank_vertex_t *ent, uint32_t mode);
void gpu3d_raster_band_bucket_classify_by_depth_hires(gpu3d_t *machine, gpu3d_band_bucket_t *list, gpu3d_polygon_list_t *objs, gpu3d_bank_vertex_t *ent, uint32_t mode);
void gpu3d_raster_band_bucket_classify_hires(gpu3d_t *machine, gpu3d_band_bucket_t *list, gpu3d_polygon_list_t *objs, gpu3d_bank_vertex_t *ent, uint32_t mode);
void gpu3d_raster_bands_group_runs(uint8_t *a0, unsigned char *base, const gpu3d_polygon_t *a2, uint8_t *a3, int cursor_start, int count, uint32_t flag, const gpu3d_bank_vertex_t *a7);
void gpu3d_raster_bands_prepare_blocks(void *param_1, void *param_2, uint32_t param_3);
void gpu3d_raster_block_summarize_and_delta(gpu3d_t *a, unsigned char *b);
void gpu3d_raster_line_window_select_and_ramp(uint8_t *param_1, void *param_2, void *param_3, const gpu3d_bank_vertex_t *const *param_4, uint32_t param_5, uint32_t param_6, int32_t param_7, uint64_t param_8);
void gpu3d_raster_band_compose_fog_alpha(unsigned char *machine, unsigned char *dest, uint32_t row);
void gpu3d_raster_band_compose_fogged(unsigned char *machine, unsigned char *dest, uint32_t row);
void gpu3d_raster_band_compose_block_pairs(gpu_t *machine);
void gpu3d_raster_band_compose_plain(unsigned char *machine, unsigned char *dest, uint32_t row);
void gpu3d_raster_band_compose_set_alpha(gpu_t *machine);
void gpu3d_raster_band_compose_scaled_fogged(void *param_1, void *param_2, uint32_t param_3);
void gpu3d_raster_band_compose_scaled_plain(void *param_1, void *param_2, uint32_t param_3);
void gpu3d_raster_band_flush_fogged(gpu_t *machine);
void gpu3d_raster_band_flush_plain(gpu_t *machine);
void gpu3d_raster_band_flush_scaled(gpu_t *machine);
void gpu3d_raster_band_pair_compose(gpu_t *machine);
void gpu3d_raster_double_buffer_init(unsigned char *base);
void gpu3d_raster_page_compose_fog_alpha(uint8_t *state, uint8_t *output);
void gpu3d_raster_deinterleave_words_blocks(unsigned char *dst, const unsigned char *src);
void gpu3d_raster_set_alpha_plane(unsigned char *dst, const unsigned char *src, const unsigned char *level, uint32_t param4);
void gpu3d_raster_swap_linked_pair_channels(uint8_t *ctx, int32_t n);
void gpu3d_raster_swap_linked_pair_channels_x2(uint8_t *ctx, int32_t n);
void gpu3d_raster_test_neighbor_edge_bordered(unsigned char *dst, const unsigned char *center, const unsigned char *neighbor, uint32_t edge);
void gpu3d_raster_test_neighbor_edge_bordered_alt(unsigned char *dst, const unsigned char *center, const unsigned char *neighbor, uint32_t edge);
void gpu3d_raster_test_neighbor_edge_bordered_x2(unsigned char *dst, const unsigned char *center, const unsigned char *neighbor, uint32_t edge);
void gpu3d_raster_test_neighbor_edge_bordered_x2_alt(unsigned char *dst, const unsigned char *center, const unsigned char *neighbor, uint32_t edge);
void gpu3d_raster_test_neighbor_edge_dual(unsigned char *dst, const unsigned char *va, const unsigned char *center, const unsigned char *vb, uint32_t edge);
void gpu3d_raster_test_neighbor_edge_dual_x2(unsigned char *dst, const unsigned char *va, const unsigned char *center, const unsigned char *vb, uint32_t edge);
void gpu3d_raster_advance_vertex_accumulators(gpu3d_t *ctx, const uint32_t *rec, const uint32_t *zeros);
void gpu3d_raster_advance_vertex_accumulators_scaled(gpu3d_t *ctx, const uint32_t *rec, const uint32_t *zeros);
void gpu3d_raster_compute_reciprocal_block(uint32_t *recip, uint32_t *zeros_out, const uint32_t *ent, uint32_t n);
void gpu3d_raster_divide_perspective_fixed(int16_t *dst, const float *src, int32_t n);
void gpu3d_raster_interp_five_ramps_rows(const gpu3d_bank_vertex_t *const *param_1, uint8_t *param_2, const int16_t *param_3, const uint8_t *param_4, int32_t param_5);
void gpu3d_raster_interp_lerp_rows(const gpu3d_bank_vertex_t *const *param_1, int32_t *param_2, const int16_t *param_3, const uint8_t *param_4, int32_t param_5);
void gpu3d_raster_scale_vertex_row(int32_t *dst, unsigned char *params, const int16_t *src, uint32_t rows);
void gpu3d_raster_blit_row_stride_256(unsigned char *dst, unsigned char *src, uint32_t width, uint32_t rows);
void gpu3d_raster_byte_fill(unsigned char *dst, uint32_t value, int32_t n);
void gpu3d_raster_fog_apply_frame(unsigned char *machine, unsigned char *frame);
void gpu3d_raster_fog_blend_alpha_line(unsigned char *dst, const unsigned char *src, const unsigned char *tbl, uint32_t w3);
void gpu3d_raster_fog_blend_color_line_512(unsigned char *dst, const unsigned char *src, const unsigned char *factor, uint32_t color);
void gpu3d_raster_fog_blend_color_split_parity(unsigned char *dst_pair, const unsigned char *src, const unsigned char *factor, uint32_t w3_color);
void gpu3d_raster_palette_blit_256(unsigned char *dst, const unsigned char *src, const unsigned char *idx, const unsigned char *pal);
void gpu3d_raster_perspective_divide_fix15(int16_t *dst, const float *numer, const float *denom, int32_t n);
void gpu3d_raster_ramp_pairs_generate(float *param_1, const gpu3d_bank_vertex_t *const *param_2, unsigned char *param_3, int param_4, int32_t param_5);
void gpu3d_raster_rgba_force_opaque(unsigned char *px, int64_t n);
void gpu3d_raster_row_fill_constants(unsigned char *tables, uint32_t *dst, uint32_t rows, uint32_t base);
void gpu3d_raster_row_ramp_generate(int *param_1, float *param_2, float *param_3, int param_4);
void gpu3d_raster_rows_copy_fixed_triple_256(uint32_t *d0, uint32_t *d1, unsigned char *d2, const uint32_t *s0, const uint32_t *s1, const unsigned char *s2, uint32_t width, uint32_t rows);
void gpu3d_raster_rows_copy_gap_masked_alpha(const unsigned char *base, unsigned char *dst_a, unsigned char *dst_b, uint32_t rows, uint32_t alpha, const unsigned char *src_a, const unsigned char *src_b, const unsigned char *mask);
void gpu3d_raster_rows_copy_masked_alpha(unsigned char *tables, uint32_t *d0, uint32_t *d1, uint32_t rows, uint32_t mark, const uint32_t *s0, const uint32_t *s1, const unsigned char *mask);
void gpu3d_raster_rows_copy_one_plane_wide(unsigned char *dst, unsigned char *src, unsigned char *tables, uint32_t rows);
void gpu3d_raster_rows_copy_table(unsigned char *dst, unsigned char *src, unsigned char *tables, uint32_t rows);
void gpu3d_raster_rows_copy_table_triple(uint32_t *d0, uint32_t *d1, unsigned char *d2, const uint32_t *s0, const uint32_t *s1, const unsigned char *s2, unsigned char *tables, uint32_t rows);
void gpu3d_raster_rows_copy_three_planes_wide(uint32_t *d0, uint32_t *d1, unsigned char *d2, const uint32_t *s0, const uint32_t *s1, const unsigned char *s2, unsigned char *tables, uint32_t rows);
void gpu3d_raster_span_copy_alpha_256(const unsigned char *param_1, uint32_t *param_2, uint32_t *param_3, int32_t param_4, unsigned char param_5, const uint32_t *param_6, const uint32_t *param_7);
void gpu3d_raster_span_copy_alpha_512(const unsigned char *param_1, uint32_t *param_2, uint32_t *param_3, int32_t param_4, unsigned char param_5, const uint32_t *param_6, const uint32_t *param_7);
void gpu3d_raster_word_fill(uint32_t *dst, uint32_t value, int32_t n);
void gpu3d_raster_depth_test_equal_lines(uint8_t *param_1, const int32_t *param_2, const uint32_t *param_3, int32_t param_4, uint32_t *param_5);
void gpu3d_raster_span_band_compose_dispatch(uint8_t *param1, uint8_t *param2, const gpu3d_polygon_t *param3, uint32_t param4, uint32_t param5, uint8_t *param6, int32_t param7, uint32_t param8, const gpu3d_bank_vertex_t *param9);
void gpu3d_raster_span_band_compose_dispatch_hires(uint8_t *state, uint8_t *entry, const gpu3d_polygon_t *order, uint32_t column, uint32_t width, uint8_t *zone, uint32_t rows, uint32_t flags, const gpu3d_bank_vertex_t *extra);
void gpu3d_raster_span_edge_ramp_dispatch(uint8_t *param_1, const gpu3d_polygon_t *param_2, const gpu3d_bank_vertex_t *param_3, uint32_t param_4, uint32_t param_5);
void gpu3d_raster_span_edge_ramp_dispatch_hires(uint8_t *param_1, const gpu3d_polygon_t *param_2, const gpu3d_bank_vertex_t *param_3, uint32_t param_4, uint32_t param_5);
void gpu3d_raster_span_edge_stream_fill(unsigned char *param_1, uint16_t *param_2, int32_t param_3, unsigned long param_4);
void gpu3d_raster_span_row_compose(uint8_t *p1, const gpu3d_polygon_t *p2, uint8_t *p3, uint32_t p4, int32_t p5, int32_t p6, int32_t p7, uint32_t p8, int32_t p9, uint32_t p10, uint32_t p11, uint32_t p12);
void gpu3d_raster_span_row_compose_hires(uint8_t *param_1, const gpu3d_polygon_t *param_2, uint8_t *param_3, uint32_t param_4, int32_t param_5, int32_t param_6, int32_t param_7, uint32_t param_8, int32_t param_9, uint32_t param_10, uint32_t param_11, uint32_t param_12);
void * gpu3d_raster_span_value_over_mask_array(uint8_t *mask, const uint32_t *thresholds, const uint32_t *values, int32_t n, uint32_t *count);
void * gpu3d_raster_texel_blend_dispatch(const unsigned char *a0, const gpu3d_t *a1, const gpu3d_polygon_t *a2, unsigned char *a3, const unsigned char *a4, unsigned char *a5, unsigned int a6, unsigned int a7, unsigned int a8);
void * gpu3d_raster_texel_blend_mono_alpha(unsigned char *dst, const unsigned char *fg, const unsigned char *plane, unsigned char alpha_const, long count);
void * gpu3d_raster_texel_blend_planar_alpha(uint8_t *dst, const uint8_t *src_fg, const uint8_t *src_bg_planes, uint32_t stride, uint32_t alpha_const, int32_t count);
void gpu3d_raster_texel_index_expand_planes(const unsigned char *tables, unsigned char *buf, uint32_t stride, int32_t n);
void * gpu3d_raster_texel_palette_table_build(uint8_t *ctx, const uint16_t *colors);
void gpu3d_raster_texel_table_lookup(uint32_t *dst, const uint32_t *src, const uint32_t *table, int32_t n);
void gpu3d_raster_texel_table_lookup_chained(uint32_t *dst, const uint32_t *src, const unsigned char *idx, const uint32_t *palette, int64_t n);
void gpu3d_raster_texel_unpack_nibbles(uint8_t *output, const uint8_t *entry, int count);
void gpu3d_raster_texture_cache_entry_build(gpu3d_texture_entry_t *node, gpu3d_texture_cache_t *ctx, uint32_t p3, uint32_t p4);
void gpu3d_raster_texture_cache_flush_entries(gpu3d_texture_cache_t *obj);
uint32_t gpu3d_raster_texture_cache_purge_dirty(gpu3d_texture_cache_t *o);
void * gpu3d_raster_texture_cache_reset(gpu3d_texture_cache_t *obj);
void gpu3d_raster_texture_data_split_bank_limit(gpu3d_texture_cache_t *cache, void *a1, uint8_t *data, unsigned size, void *a4, unsigned channel, unsigned shift, unsigned mode, unsigned extra);
void gpu3d_raster_texture_decode_4x4_compressed(void *node_v, uint32_t *texel_bits, const uint16_t *block_idx, uint32_t pltt_base8, void *const *pltt_banks);
void gpu3d_raster_texture_format_decode(uint8_t *node, uint8_t *dest, uint8_t *origin, const uint16_t *palette, uint32_t format, uint32_t size, int32_t color0);
void gpu3d_raster_texture_wrap_dispatch(uint8_t *param_1, uint32_t *dst, const int16_t *xy, int32_t n, const uint8_t *val);
void gpu3d_raster_band_thread_run(void *ctx);
void gpu3d_raster_frame_dispatch(gpu_t *gpu, uint32_t mode);
void gpu3d_raster_frame_dispatch_hires(gpu_t *gpu, uint32_t mode);
void gpu3d_raster_frame_dispatch_select(gpu_t *gpu, uint32_t mode);
int gpu3d_raster_frame_thread_publish(void *ctx);
void gpu3d_raster_frame_thread_run(void *ctx);
int gpu3d_raster_frame_thread_submit(void *ctx, uint32_t selector);
void * gpu3d_raster_scanline_lookup_filtered(gpu_t *param_1, int param_2);
uint32_t math_sqrt_u32(uint32_t num);
int32_t input_shared_region_create(const char *name, uint32_t size);
uint32_t io7_read16(unsigned char *ctx, uint32_t dir);
void io7_write16(void *ctx, uint32_t reg, uint32_t val);
void io7_write8(bus_t *param_1, uint32_t param_2, uint32_t param_3);
uint32_t io9_read16(unsigned char *ctx, uint32_t dir);
void io9_write16(void *ctx, uint32_t reg, uint32_t val);
void io9_write8(void *ctx, uint32_t reg, uint32_t val);
uint32_t io_bank15870_read32_lazy_init(unsigned char *state, uint32_t dir);
int32_t io_exmemcnt_gba_slot_arm7_mask(const unsigned char *obj, uint32_t dir);
int io_exmemcnt_gba_slot_arm7_mask_clone(unsigned char *cpu, uint32_t dir);
int32_t io_exmemcnt_gba_slot_arm7_mask_clone2(const unsigned char *obj, uint32_t dir);
int io_exmemcnt_gba_slot_arm9_mask(unsigned char *cpu, uint32_t dir);
int32_t io_exmemcnt_gba_slot_arm9_mask_byte(const unsigned char *obj, uint32_t dir);
int io_exmemcnt_gba_slot_arm9_mask_word(unsigned char *cpu, uint32_t dir);
uint32_t io_reg_cache_read16_init(unsigned char *state, uint32_t dir);
uint32_t io_reg_cache_read8_init(unsigned char *state, uint32_t dir);
void io_reg_cache_write16_init(uint8_t *state, unsigned dir, unsigned value);
void io_reg_cache_write32_init(uint8_t *state, unsigned dir, unsigned value);
void io_reg_cache_write8(unsigned char *state, uint32_t dir, uint32_t value);
void io_reg_cache_write8_init(uint8_t *state, unsigned dir, unsigned value);
int32_t io_slot2_gpio_read8_idle(uint64_t param_1, uint32_t param_2);
void io_slot2_gpio_write16(uint8_t *ctx, uint64_t param_2, uint32_t param_3);
void io_slot2_gpio_write32(uint8_t *ctx, uint64_t param_2, uint32_t param_3);
void io_slot2_gpio_write8(uint8_t *ctx, uint64_t param_2, uint32_t param_3);
uint32_t mirror_dirty_bitmap_test(const uint32_t *coarse, const uint32_t *fine, uint32_t address, uint32_t len);
void mirror_fatal_reset_longjmp(unsigned char *param_1);
void * mirror_get_fixed_page_ptr(void);
int32_t mirror_memory_subsystem_create(uint8_t *param_1, uint8_t *param_2);
int32_t mirror_memory_subsystem_destroy(uint8_t *param_1);
int mirror_query_unsupported(void *machine, const char *path, uint32_t per_game);
void mirror_pause_hook_noop(void);
int32_t mirror_shm_create(const char *name, uint32_t size, int32_t level_api);
uint32_t mirror_write_block_via_regions(unsigned char *table, void *ctx, uint32_t dir, unsigned char *origin, uint32_t remaining);
int32_t vram_entry_compare_by_field8(const void *param_1, const void *param_2);
uint32_t vram_reg_cache_read32_init(uint8_t *param_1, uint64_t param_2);
uint8_t vram_reg_cache_read8_init(uint8_t *param_1, uint64_t param_2);
void vram_reg_cache_write16_init(uint8_t *state, unsigned dir, unsigned value);
void vram_reg_cache_write32_init(uint8_t *state, unsigned dir, unsigned value);
void vram_reg_cache_write8(uint8_t *state, uint32_t dir, uint32_t value);
void vram_reg_cache_write8_init(uint8_t *state, unsigned dir, unsigned value);
void * vram_resolve_cell_ptr_coarse(void *unused, unsigned char *entry, uint32_t dir);
void * vram_resolve_cell_ptr_fine(void *unused, unsigned char *entry, uint32_t dir);
void * vram_resolve_ptr_bank14_first_pair(bus_t *bus, uint32_t dir);
void * vram_resolve_ptr_bank14_second_pair(bus_t *bus, uint32_t dir);
void * vram_resolve_ptr_bank17(bus_t *bus, uint32_t dir);
void * vram_resolve_ptr_bank17_diverted(bus_t *bus, uint32_t dir);
unsigned char * vram_resolve_ptr_bus_tagged(bus_t *bus, uint32_t dir);
void * vram_resolve_ptr_region10(bus_t *bus, uint32_t dir);
long vram_resolve_ptr_returns_null(long a0, long a1, long a2, long a3, long a4, long a5, long a6, long a7);
void * vram_resolve_slot64(bus_t *bus, unsigned char *obj, uint32_t dir);
void * vram_resolve_slot_page64k(bus_t *bus, unsigned char *obj, uint32_t dir);
void vram_vramcnt_bank_remap(vram_map_t *vram, uint8_t *bank_data, unsigned int idx, unsigned int attrs, unsigned int mode);
void vram_vramcnt_write_cascade(vram_map_t *vram, uint8_t *bank_data, unsigned idx, unsigned updated);
uint32_t vram_write_cache_read16_lazy(uint8_t *state, uint32_t param_2);
void platform_audio_output_feed_frame(spu_t *spu);
void crash_write_dump_report(void *param_1);
void platform_config_record_reset(void);
void files_descriptor_free(void **obj);
void * files_jni_call_static_method_build_result(const char *arg0, const char *arg1);
uint32_t files_jni_env_invoke_alternate(void *arg);
uint32_t files_jni_env_invoke_and_release(const char *arg0, const char *arg1);
void * files_fopen_resolved(const char *path, const char *mode);
int files_open_translate_flags(const char *path, int flags);
int files_read_exact_size(unsigned char *obj, const char *name, void *dest, uint32_t expected_size);
int files_stat_resolved(const char *path, void *buf);
int platform_doublebuffer_flip_signal(void);
int platform_doublebuffer_signal(void);
int platform_doublebuffer_wait(void);
struct tm * recon_clock_localtime(const time_t *t);
time_t recon_clock_time(time_t *t);
void time_now_microseconds(uint64_t *dest);
uint32_t rtc_register_write(rtc_t *r, uint32_t arg);
int firmware_build_path(char *dest, long a, long b, long c, ...);
void * firmware_header_build(firmware_header_t *h);
void firmware_mount(spi_t *spi, nds_t *machine);
void firmware_user_settings_build(const uint32_t *str, uint8_t *image);
void spi_memory_address_wrap(spi_memory_t *m, uint32_t mask);
int spi_memory_close_file(spi_memory_t *m);
void spi_memory_deselect(spi_memory_t *m);
long spi_memory_mount(spi_memory_t *m, uint32_t type, unsigned char *buf, uint32_t size, const char *path, uint32_t fa, uint32_t fb);
uint32_t spi_memory_read_word(spi_memory_t *m);
void spi_memory_reset(spi_memory_t *m);
long spi_memory_save_file(spi_memory_t *m);
char * spi_memory_set_path(spi_memory_t *m, const char *str);
uint32_t spi_memory_transfer_byte(spi_memory_t *m, uint32_t value);
void spi_memory_write_word(spi_memory_t *m, uint32_t param_2);
void spi_control_write(spi_t *spi, uint32_t value);
void spi_reset(spi_t *spi);
uint32_t spi_transfer_byte(spi_t *spi, uint32_t value);
void spi_tsc_set_position(spi_tsc_t *tsc, uint32_t a, uint32_t b);
void spu_mixer_accumulate_pair(int16_t *dst, int32_t *acc, const int16_t *coef, int32_t n, uint32_t off);
void spu_mixer_accumulate_triple(uint8_t *param_1, int16_t *param_2, int32_t *param_3, int32_t param_4, uint32_t param_5);
void spu_mixer_run_channels(spu_t *spu, unsigned char *output, uint32_t n);
void spu_mixer_run_frame(unsigned char *machine);
unsigned spu_resample_sample_by_time(spu_t *spu, uint64_t elapsed);
void spu_channel_advance_position(spu_t *spu, void *unused, uint32_t samples, uint32_t channel);
void spu_channel_set_mode_and_resize(uint32_t slot, uint32_t mode);
void spu_channel_start(spu_t *spu, uint32_t ch);
void spu_init_channels_and_noise(spu_t *spu, unsigned char *ctx);
void spu_recording_start(spu_t *spu);
void spu_recording_stop(spu_t *spu);
void spu_slot_activate(spu_t *spu, uint32_t slot, uint32_t state);
uint64_t util_bsearch_key_by_id(const game_database_t *ctx, uint32_t key);
uint32_t util_crc32_buffer_padded(const unsigned char *data, uint32_t len);
int32_t str_compare_u32_unsigned(const void *a, const void *b);
int str_qsort_compare_u32_at_28(const void *a, const void *b);
int str_qsort_compare_u32_at_36(const void *a, const void *b);
char * str_scan_until_tag_separator(char *s);
char * str_skip_whitespace(char *s);
int str_sprintf_limited(char *dest, size_t size, const char *format, ...);
int str_vsnprintf_limited_swapped_args(char *dest, size_t slen, size_t maxlen, const char *format, ...);
int str_vsprintf_caller_limit_1(char *dest, size_t size, const char *format, ...);
int str_vsprintf_caller_limit_2(char *dest, size_t size, const char *format, ...);
int str_vsprintf_caller_limit_3(char *dest, size_t size, const char *format, ...);
int str_vsprintf_caller_limit_4(char *dest, size_t size, const char *format, ...);
int str_vsprintf_fixed_format_2080(char *dest, long a, long b, ...);
int str_vsprintf_limit_1024(char *dest, long unused, const char *format, ...);
int str_vsprintf_limit_2080_1(char *dest, long unused, const char *format, ...);
int str_vsprintf_limit_2080_2(char *dest, long unused, const char *format, ...);
int str_vsprintf_limit_256(char *dest, long unused, const char *format, ...);

extern const int32_t bus_cost_same_region[64];
extern const int32_t bus_cost_cross_region[64];
void gpu2d_deferred_capture_queue_push(gpu2d_engine_t *engine, uint32_t a,
                                      uint32_t b, uint32_t c, uint32_t d);
void *video_out_clear_large_buffer(unsigned char *obj);
long nds_subsystem_notify_shutdown_pair(unsigned char *obj);

void gpu3d_poly_commit_pending_batch(gpu3d_t *ctx);

void gpu3d_io3d_color_cache_primary_store(gpu3d_t *base, uint32_t idx, uint32_t color);
void gpu3d_io3d_color_cache_secondary_store(gpu3d_t *base, uint32_t idx, uint32_t color);
void gpu3d_io3d_store_7bit_value(gpu3d_t *base, uint32_t idx, uint32_t value);

void arm_debug_init(struct arm_debug *debug, arm_t *owner);
void benchmark_init(unsigned char *obj, nds_t *machine, uint32_t b, uint32_t c, uint32_t unused, uint32_t f);
void benchmark_step(unsigned char *o);
void bus_map_reset(unsigned char *machine);
int cart_open_rom(cart_t *cart, char *path);
void config_unpack_word(unsigned char *obj);
uint64_t dma_channel_run_transfer(dma_t *machine, dma_channel_t *channel);
void gpu2d_compose_build_layer_order(gpu2d_engine_t *r);
void * gpu2d_engine_init_slot(gpu2d_engine_t *obj, uint32_t idx, gpu_t *gpu);
void * gpu2d_line_process_range(gpu2d_engine_t *obj, uint32_t start, uint32_t end, void *arg);
void gpu2d_obj_scan_oam(gpu2d_engine_t *R);
void * gpu3d_context_init(gpu3d_t *o);
void gpu3d_poly_detect_axis_rect_fastpath(unsigned char *o, unsigned char *ent);
void gpu3d_raster_blend_fog_line(unsigned char *dst, const unsigned char *src, const unsigned char *factor, uint32_t color);
long gpu3d_raster_pipeline_init(gpu_t *obj);
void gpu3d_raster_pixel_alpha_max(uint8_t *param_1, const uint8_t *param_2, int32_t param_3, uint8_t *param_4);
void gpu3d_raster_pixel_blend_alpha(uint8_t *param_1, const uint8_t *param_2, int32_t param_3, uint8_t *param_4);
void gpu3d_raster_planes_interleave_rgba(unsigned char *dst, const unsigned char *src, uint32_t stride, int32_t n, uint32_t quarter);
void * gpu3d_raster_texture_cache_init(gpu3d_texture_cache_t *obj, void *origin);
void * gpu3d_raster_texture_cache_lookup_or_create(gpu3d_texture_cache_t *base, uint32_t key, uint32_t sub);
void gpu3d_raster_words_copy_mask29(uint32_t *dest, const uint32_t *origin);
void gpu_frame_close(uint8_t *ctx);
void gpu_frame_open(uint8_t *ctx);
void input_poll_and_pause(uint8_t *ctx);
void input_record_end_of_frame(uint8_t *p);
long input_record_load(unsigned char *obj);
void jit_arena_regions_init(unsigned char *arena);
void mem_console_reset(uint8_t *param_1);
void pagetable_dtcm_remap(bus_t *bus, uint32_t base, uint32_t len);
void pagetable_itcm_resize(bus_t *bus, uint32_t updated_size);
long spi_memory_save_tick(spi_memory_t *m);
long spu_reset_slots_and_load_config(spu_t *spu);
void audio_out_resume_after_stop(spu_t *spu, uint32_t stop_result);
void spu_adpcm_decode_block(void *channel);

void gpu2d_worker_hook_noop(void);
void video_out_gl_init_hook_noop(void);
void audio_out_set_runtime_flag(uint32_t a0);
void audio_out_set_enabled_flag(uint32_t a0);
long system_set_config_byte(long a0);

uint32_t archive_7z_name_from_utf16(void *param_1, const void *param_2);
int32_t archive_rom_extension_is_supported(const char *param_1);
int archive_rom_read_reordered_block(const char *param_1, void *param_2);
void archive_rom_reader_destroy(uint8_t *param_1);
void arm_debug_set_mode(unsigned char *obj, uint32_t v);
void audio_out_set_mode_word(uint32_t a0);
long audio_out_set_runtime_word(long a0);
uint32_t bus_read16(unsigned char *table, uint32_t dir);
uint32_t bus_read32(unsigned char *table, uint32_t dir);
uint32_t bus_read8(uint8_t *param_1, uint32_t param_2);
void cart_sensor_write_accel_axes_16bit(float param_1, float param_2, float param_3, slot2_sensor_t *sensor);
void cart_sensor_write_accel_axes_8bit(float param_1, float param_2, float param_3, slot2_sensor_t *sensor);
void cart_sensor_write_gyro_16bit(float param_1, slot2_sensor_t *sensor);
uint32_t cart_slot2_map(unsigned char *ctx, uint8_t *rom, uint32_t size);
uint32_t cheats_list_add_entry(unsigned char *context, const char *name, const void *codes, uint32_t count);
void dma_channel_finish_transfer(void *const *pair, dma_channel_t *channel, cart_t *ctx);
void * dma_main_memory_display_step(uint8_t *bus, dma_channel_t *channel, uint32_t line);
void gpu2d_bg_affine_texcoord_pack_batched(const unsigned char *texture, unsigned char *output, int count, int base_u, int base_v, int step_u, int step_v, int mask, int shift);
void gpu2d_bg_affine_texcoord_pack_scalar(const uint8_t *texture, uint8_t *output, int count, int base_u, int base_v, int step_u, int step_v, int mask, int shift);
void gpu2d_bg_text_apply_mosaic_layers(gpu2d_engine_t *ctx, uint8_t *dsts, uint8_t *auxs, uint32_t line);
void gpu2d_bg_text_compute_span_range(int32_t x, int32_t a, int32_t b, int32_t c, int64_t *out_a, int64_t *out_b, int64_t *out_c);
void gpu2d_bg_text_decode_4bpp_line(uint8_t *out_color, uint8_t *out_idx, const uint8_t *palettes, const uint8_t *tiledata, const uint16_t *map, const uint32_t *attrs);
void gpu2d_bg_text_decode_8bpp_indices_line(uint8_t *output, const uint8_t *tiledata, const uint16_t *map, const uint32_t *attrs);
void gpu2d_bg_text_decode_8bpp_line(uint8_t *output, const uint8_t *tiledata, const uint16_t *map, const uint32_t *attrs);
void gpu2d_bg_text_mask_4bpp_line_shifted(uint8_t *output, const uint8_t *indices, int shift);
void gpu2d_bg_text_pack_blend_window(uint16_t *out_px, uint8_t *out_height, const uint16_t *block_a, const uint16_t *block_b, int k, int blend);
void gpu2d_bg_text_pack_blend_window_wide(uint16_t *out_px, uint8_t *out_height, const uint16_t *block_a, const uint16_t *block_b, int k, int blend);
void gpu2d_blend_apply_brightness(const gpu2d_engine_t *state, uint8_t *dest, const uint8_t *source, const uint16_t *mask);
void gpu2d_compose_convert_texels_to_rgb555_modulated(const gpu_output_t *ctx, uint8_t *dst, const uint8_t *blend_src, const uint8_t *texels);
void gpu2d_compose_decode_bg_row_8bpp_indexed(uint8_t *x0, uint8_t *x1, uint8_t *x2, uint8_t *x3, uint8_t *x4, int32_t x5, uint8_t *x6);
void gpu2d_compose_mark_empty_groups(const unsigned char *data, uint32_t *mask);
void gpu2d_compose_pack_planes_to_rgb15(const gpu_output_t *ctx, uint8_t *dst, const uint8_t *planes);
void gpu2d_compose_pack_rgba_to_rgb15(const gpu_output_t *ctx, uint8_t *dst, const uint8_t *src);
void gpu2d_compose_resolve_visibility(const uint8_t *obj, const uint8_t *masks, uint8_t *output);
void gpu2d_compose_resolve_visibility_layered_pair(const uint8_t *obj, const uint8_t *masks, uint8_t *above, uint8_t *below);
void gpu2d_compose_split_rgb_planes(uint8_t *dest, const uint16_t *origin);
void gpu2d_engine_reset_bg_cache_ptrs(gpu2d_engine_t *obj);
void gpu2d_engine_select_bg_handlers(gpu2d_engine_t *o);
void gpu2d_line_apply_layer_masked(uint16_t *dest, const uint16_t *a, const uint16_t *b, const uint32_t *mask);
void gpu2d_line_finish(uint8_t *ctx, uint32_t line);
uint32_t gpu2d_obj_draw_line(gpu2d_engine_t *ctx, uint8_t *px, uint8_t *atr, uint8_t *layers, uint8_t *m_bit7, uint8_t *m_bits05, uint32_t line);
void gpu2d_palette_lookup_line_idx16(uint16_t *buf, const unsigned char *table, int32_t n);
void gpu2d_palette_translate_indices8_pack(uint16_t *buf, const unsigned char *table, int32_t n);
void gpu2d_planes_split_interleaved_masked(uint8_t *dest, uint8_t *quarter, const uint8_t *source, const uint16_t *mask);
void gpu2d_window_regions_apply_four(void *param_1, void *param_2, uint32_t param_3, void *param_4, void *param_5, void *param_6, uint32_t param_7, uint32_t param_8, uint32_t param_9, uint32_t param_10);
void gpu3d_geometry_clip_edge(uint8_t *out, const uint8_t *a, const uint8_t *b, uint32_t sel);
unsigned int gpu3d_io3d_color_cache_primary_read(const gpu3d_t *state, unsigned int idx);
unsigned int gpu3d_io3d_color_cache_secondary_read(const gpu3d_t *state, unsigned int idx);
void gpu3d_matrix_transform_and_clip_code(gpu3d_t *ctx);
void gpu3d_raster_band_draw_dispatch(unsigned char *machine);
void gpu3d_raster_band_pending_process(void *param_1);
void gpu3d_raster_blit_row_stride_512(unsigned char *dst, unsigned char *src, uint32_t width, uint32_t rows);
void gpu3d_raster_fog_blend_alpha_split_parity(unsigned char *dst, const unsigned char *src, const unsigned char *table, uint32_t param4);
void gpu3d_raster_fog_density_line(const unsigned char *src, unsigned char *dst, const unsigned char *tables, uint32_t pair);
void gpu3d_raster_fog_density_line_512(const unsigned int *param_1, unsigned char *param_2, const unsigned char *param_3, uint32_t param_4);
void gpu3d_raster_palette_blit_deinterleave_512(unsigned char *dst, const unsigned char *src, const unsigned char *idx, const unsigned char *pal);
void gpu3d_raster_rows_copy_fixed_triple_512(uint32_t *d0, uint32_t *d1, unsigned char *d2, const uint32_t *s0, const uint32_t *s1, const unsigned char *s2, uint32_t width, uint32_t rows);
void gpu3d_raster_span_component_gate_filter(uint8_t *param_1, const uint8_t *param_2, uint8_t param_3, int32_t param_4, uint32_t *param_5);
void gpu3d_raster_span_key_tolerance_mask(uint8_t *param_1, uint32_t param_2, const uint32_t *param_3, int32_t param_4, uint32_t *param_5);
void gpu3d_raster_span_layer_color_mask_clear(unsigned char *mask, const unsigned char *layer, const unsigned char *other, int32_t n, uint32_t color);
void gpu3d_raster_span_run_batch_flush_hires(uint8_t *a0, unsigned char *base, const gpu3d_polygon_t *a2, uint8_t *a3, int cursor_start, int count, uint32_t flag, const gpu3d_bank_vertex_t *a7);
unsigned gpu3d_raster_span_value_over_mask(uint8_t *mask, uint32_t threshold, const uint32_t *values, int n, uint32_t *count);
void gpu3d_raster_wrap_texel_clamp_clamp(uint32_t *dst, const int16_t *xy, int32_t n, uint32_t width, uint32_t height, const uint8_t *val);
void gpu3d_raster_wrap_texel_clamp_mirror(uint32_t *dst, const int16_t *xy, int32_t n, uint32_t width, uint32_t height, const uint8_t *val);
void gpu3d_raster_wrap_texel_clamp_repeat(uint32_t *dst, const int16_t *xy, int32_t n, uint32_t width, uint32_t height, const uint8_t *val);
void gpu3d_raster_wrap_texel_mirror_clamp(uint32_t *dst, const int16_t *xy, int32_t n, uint32_t width, uint32_t height, const uint8_t *val);
void gpu3d_raster_wrap_texel_mirror_mirror(uint32_t *dst, const int16_t *xy, int32_t n, uint32_t width, uint32_t height, const uint8_t *val);
void gpu3d_raster_wrap_texel_mirror_repeat(uint32_t *dst, const int16_t *xy, int32_t n, uint32_t width, uint32_t height, const uint8_t *val);
void gpu3d_raster_wrap_texel_repeat_clamp(uint32_t *dst, const int16_t *xy, int32_t n, uint32_t width, uint32_t height, const uint8_t *val);
void gpu3d_raster_wrap_texel_repeat_mirror(uint32_t *dst, const int16_t *xy, int32_t n, uint32_t width, uint32_t height, const uint8_t *val);
void gpu3d_raster_wrap_texel_repeat_repeat(uint32_t *dst, const int16_t *xy, int32_t n, uint32_t width, uint32_t height, const uint8_t *val);
void input_record_close_write_stream(unsigned char *obj);
int32_t input_record_load_playback_buffer(unsigned char *param_1, const char *param_2);
void input_record_open_write_stream(unsigned char *param_1, const char *param_2);
int32_t jit_cache_flush(uint8_t *ctx, uint32_t arg);
uint32_t jit_emit_operand_word_ext(jit_emitter_t *param_1, uint32_t param_2, int32_t param_3);
int mirror_alias_blocks_16k(bus_t *bus, uint8_t *base, unsigned size, unsigned offset_base);
int nds_frame_limiter_measure_returns_zero(void);
void script_invoke_on_load(const char *path);
uint32_t script_is_active(void);
int state_load_file(unsigned char *machine, const char *path, unsigned char *top, unsigned char *bottom, uint32_t only_look);
int state_load_slot(unsigned char *obj, uint32_t slot, void *a2, void *a3, uint32_t a4);
int32_t state_save_slot(unsigned char *obj, uint32_t slot, void *a3, void *a4);
int str_vsprintf_caller_limit_5(char *dest, size_t size, const char *format, ...);
int video_out_gl_compile_shader_program(const char *const *vertex_src, const char *const *fragment_src, void *program_info, char **out_error);
int32_t video_out_gl_load_shader_recipe_slot0(const char *param_1, uint32_t param_2, uint32_t param_3);
int32_t video_out_gl_load_shader_recipe_slot1(const char *param_1, uint32_t param_2, uint32_t param_3);
void video_out_gl_renderer_draw_passes(void *param_1, uint32_t param_2, int32_t param_3, int32_t param_4, uint32_t param_5, uint32_t param_6);
void video_out_upload_screen_textures(uint32_t texture_first, uint32_t texture_second, uint32_t idx);
void wram_apply_wramcnt(bus_t *bus);

void fortify_fail(void);
int fortify_vsprintf(char *dest, size_t size, const char *format, va_list ap);
int fortify_vsnprintf(char *dest, size_t count, size_t size, const char *format, va_list ap);
char *fortify_strcpy(char *dest, const char *src, size_t size);
size_t fortify_strlen(const char *s, size_t size);
char *fortify_strrchr(const char *p, int ch, size_t size);
char *fortify_strncpy(char *dest, const char *src, size_t n, size_t dest_size, size_t src_size);
void *fortify_memcpy(void *dest, const void *src, size_t count, size_t size);
void *fortify_memset(void *dest, int byte, size_t count, size_t size);
ssize_t fortify_read(int fd, void *buf, size_t count, size_t size);
int fortify_open(const char *path, int flags);

#endif
